theme: jekyll-theme-minimal

# Site settings
title: Daniil Marichuk
telegram_username: d_marichuk
name: Daniil Marichuk

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/dmarichuk

#Any buzzword skills you want to include
skills:
 - Python
 - Flask
 - Django
 - HTML, CSS, JS
 - Docker
 - Git
 - Linux

#Work experience is required
roles:
 - title: Developer
   start: 2020-05-12
   end: Ongoing
   employer: RusMolco
   description: RusMoclo is a part of international company Olam Food Ingredients and specialize on high quality milk production.<br>As a developer, I extract clean and aggregate data from different dairy systems and represent it on different dashboards.
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2019
   subject: Foreign languages(German, French)
   school: Penza State University

#This section is optional (as is the image link below)
yandex-praktikum:
   courses:
    - title: Backend-Development
      link: https://practicum.yandex.com/
      optionalimage: https://hsto.org/getpro/moikrug/uploads/education_platform/000/000/035/logo/medium_9029ac948c9751ee1ad303e78f4f03c8.png
      date: June 1, 2021

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  My bio.
